[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run build:api",
  "cd apps/api && npx prisma generate"
]

[start]
cmd = "npm run start:prod"
